sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "lts/*"
  - "node"

addons:
  hosts:
    - nic.localhost
    - tim.localhost
    - nicola.localhost

before_install:
  - echo "No GitHub dependencies allowed" &&
    ! grep '"github:' package-lock.json
  - npm install -g npm@latest

install:
  - npm ci

script:
  # Test the code
  - npm run standard
  - npm run validate
  - npm run nyc
  # Test global install of the package
  - npm pack .
  - npm install -g solid-server-*.tgz

after_success:
  - snyk monitor

cache: npm

notifications:
  email:
  - solid@janeirodigital.com
  - solid-travis@inrupt.com
