sudo: false
language: node_js
node_js:
  - "8.0"
  - "10.0"
  - "node"

addons:
  hosts:
    - nic.localhost
    - tim.localhost
    - nicola.localhost

before_install:
  - npm install -g npm@latest

install:
  - npm ci

script:
  # Test the code
  - npm run standard
  - npm run nyc
  # Test global install of the package
  - npm pack .
  - npm install -g solid-server-*.tgz

after_success:
  - snyk monitor

notifications:
  email:
  - solid@janeirodigital.com
  - solid-travis@inrupt.com
